/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestiontache.vue;

import com.gestiontache.controleur.ServiceIlocal;
import com.gestiontache.controleur.ServiceImpl;
import static com.gestiontache.controleur.ServiceImpl.conn;
import com.gestiontache.metier.Membre;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author samy
 */
public class AjoutermembreFr extends javax.swing.JInternalFrame {
ServiceIlocal se = new ServiceImpl();
	static List<Membre> listmemb;
        public java.sql.Statement st;
	public  ResultSet rst;
	public static PreparedStatement pst;
    /**
     * Creates new form AjoutermembreFr
     */
    public AjoutermembreFr() {
        initComponents();
    }
	public Membre membre=new Membre();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidmembre = new javax.swing.JTextField();
        txtprenommembre = new javax.swing.JTextField();
        txtnommembre = new javax.swing.JTextField();
        txtadressemembre = new javax.swing.JTextField();
        txttelmembre = new javax.swing.JTextField();
        txtemailmembre = new javax.swing.JTextField();
        btnajoutermembre = new javax.swing.JButton();
        btnvider = new javax.swing.JButton();
        btnmodifiermembre = new javax.swing.JButton();
        btnsup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmembre = new javax.swing.JTable();
        txtrecherche = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Membre"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("ID Tache");

        jLabel2.setText("Nom");

        jLabel3.setText("Prenom");

        jLabel4.setText("Adresse");

        jLabel5.setText("Telephone");

        jLabel6.setText("Email");

        txtidmembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidmembreActionPerformed(evt);
            }
        });

        txtnommembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnommembreActionPerformed(evt);
            }
        });

        txtadressemembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadressemembreActionPerformed(evt);
            }
        });

        txttelmembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelmembreActionPerformed(evt);
            }
        });

        txtemailmembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailmembreActionPerformed(evt);
            }
        });

        btnajoutermembre.setText("Ajouter");
        btnajoutermembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutermembreActionPerformed(evt);
            }
        });

        btnvider.setText("Vider");
        btnvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviderActionPerformed(evt);
            }
        });

        btnmodifiermembre.setText("modifier");
        btnmodifiermembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifiermembreActionPerformed(evt);
            }
        });

        btnsup.setText("Supprimer");
        btnsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupActionPerformed(evt);
            }
        });

        tbmembre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID membre", "Nom", "Prenom", "Adresse", "Tel", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmembre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmembreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmembre);
        if (tbmembre.getColumnModel().getColumnCount() > 0) {
            tbmembre.getColumnModel().getColumn(0).setResizable(false);
            tbmembre.getColumnModel().getColumn(1).setResizable(false);
            tbmembre.getColumnModel().getColumn(2).setResizable(false);
            tbmembre.getColumnModel().getColumn(3).setResizable(false);
            tbmembre.getColumnModel().getColumn(4).setResizable(false);
            tbmembre.getColumnModel().getColumn(5).setResizable(false);
        }

        txtrecherche.setToolTipText("Rechercher par");
        txtrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrechercheKeyReleased(evt);
            }
        });

        jLabel7.setText("Rechercher");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtemailmembre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelmembre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtadressemembre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprenommembre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidmembre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnommembre, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnajoutermembre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmodifiermembre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnvider, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(txtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtidmembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnommembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtprenommembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtadressemembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txttelmembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtemailmembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajoutermembre)
                    .addComponent(btnvider)
                    .addComponent(btnmodifiermembre)
                    .addComponent(btnsup)
                    .addComponent(txtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtidmembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidmembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidmembreActionPerformed

    private void txtnommembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnommembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnommembreActionPerformed

    private void txtadressemembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadressemembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadressemembreActionPerformed

    private void txttelmembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelmembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelmembreActionPerformed

    private void txtemailmembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailmembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailmembreActionPerformed

    private void btnajoutermembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutermembreActionPerformed
        // TODO add your handling code here:
       ajouterMembre();
    }//GEN-LAST:event_btnajoutermembreActionPerformed

    private void btnmodifiermembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifiermembreActionPerformed
        // TODO add your handling code here:
				modifierMembre();
    }//GEN-LAST:event_btnmodifiermembreActionPerformed

    private void btnsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupActionPerformed
        // TODO add your handling code here:
       supprimerMembre();
    }//GEN-LAST:event_btnsupActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        listemembre();
        Enablebutton();
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrechercheKeyReleased
        // TODO add your handling code here:
        rechercherpar();
    }//GEN-LAST:event_txtrechercheKeyReleased

    private void tbmembreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmembreMouseClicked
        // TODO add your handling code here:
        int index = tbmembre.getSelectedRow();
        TableModel mod = tbmembre.getModel();
        Enablebutton();
        txtidmembre.setText(mod.getValueAt(index, 0).toString());
        txtnommembre.setText(mod.getValueAt(index, 1).toString());
        txtprenommembre.setText(mod.getValueAt(index, 2).toString());
        txtadressemembre.setText(mod.getValueAt(index, 3).toString());
        txttelmembre.setText(mod.getValueAt(index, 4).toString());
        txtemailmembre.setText(mod.getValueAt(index, 5).toString());
    }//GEN-LAST:event_tbmembreMouseClicked

    private void btnviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviderActionPerformed
        // TODO add your handling code here:
        cleartextbox();
        Disablebutton();
    }//GEN-LAST:event_btnviderActionPerformed
 /*Tous les methodes*/
    
/*Clear textbox */
	private void cleartextbox() {
		// TODO Auto-generated method stub
		txtidmembre.setText(null);
		txtnommembre.setText(null);
		txtprenommembre.setText(null);
		txtadressemembre.setText(null);
		txttelmembre.setText(null);
		txtemailmembre.setText(null);
	
	}
        private void Disablebutton() {
		// TODO Auto-generated method stub
                btnajoutermembre.setEnabled(true);
		btnmodifiermembre.setEnabled(false);
                btnvider.setEnabled(false);
                btnsup.setEnabled(false);	
	}
         private void Enablebutton() {
		// TODO Auto-generated method stub
                btnajoutermembre.setEnabled(false);
		btnmodifiermembre.setEnabled(true);
                btnvider.setEnabled(true);
                btnsup.setEnabled(true);	
	}
          /*methode Ajouter un membre*/
         public void ajouterMembre()
         {
              membre.setMembreID(new Integer(txtidmembre.getText()));
			membre.setMembreNom(txtnommembre.getText());
			membre.setMembrePrenom(txtprenommembre.getText());
			membre.setMembreAdresse(txtadressemembre.getText());
			membre.setMembreTel(txttelmembre.getText());
			membre.setMembreEmail(txtemailmembre.getText());
		String rep=se.ajouter_membre(membre);	
		if(rep.equals("valider"))
		{
			JOptionPane.showMessageDialog(AjoutermembreFr.this, "Membre enregistre", "Information Message", 1);
			cleartextbox();
                        listemembre();
                        Disablebutton();
		}
		else
		{
			JOptionPane.showMessageDialog(AjoutermembreFr.this, "Enregistrement echoue", "Information Message", 1);
			
		}
         }
          /*methode Modifier une membre*/
         public void modifierMembre()
         {
         membre.setMembreID(new Integer(txtidmembre.getText()));
				membre.setMembreNom(txtnommembre.getText());
				membre.setMembrePrenom(txtprenommembre.getText());
				membre.setMembreAdresse(txtadressemembre.getText());
				membre.setMembreTel(txttelmembre.getText());
				membre.setMembreEmail(txtemailmembre.getText());
			String rep=	se.modifier_membre(membre);	
			if(rep.equals("valider"))
			{
				JOptionPane.showMessageDialog(AjoutermembreFr.this, "Membre Modifie", "Information Message", 1);
				cleartextbox();
                                listemembre();
                                Disablebutton();
			}
			else
			{
				JOptionPane.showMessageDialog(AjoutermembreFr.this, "Modification echoue", "Information Message", 1);
				
			}
         }
          /*methode Supprimer un membre*/
         public void supprimerMembre()
         {
          String rep=se.supprimer_membre(new Integer(txtidmembre.getText()));
				if(rep.equals("valider"))
				{
					JOptionPane.showMessageDialog(AjoutermembreFr.this, "Membre supprime", "Information Message", 1);
					cleartextbox();
                                        listemembre();
                                        Disablebutton();
				}
				else
				{
					JOptionPane.showMessageDialog(AjoutermembreFr.this, "Supression echoue", "Information Message", 1);
					
				}
         }
          /*methode lister tous les membres*/
        public  void listemembre() {
	try 
        {
            String rek="Select idmembre as ID,membrenom as Nom,membreprenom as Prenom,membreadresse as Adresse,"
                    + "membretel as Telephone,membreemail as Email "
                    + "from tb_membre "; 
            //con=DriverManager.getConnection(chainConnection,user,password);
            pst=conn.prepareStatement(rek);
            rst = pst.executeQuery();
            tbmembre.setModel(DbUtils.resultSetToTableModel(rst));
             }
        
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null,"Erreur Requette"+ se.getMessage());
                
            }
	
}
         /*methode rechercher un membre avec critere*/
        public  void rechercherpar() {
         try 
        {
            String rek="Select idmembre as ID,membrenom as Nom,membreprenom as Prenom,membreadresse as Adresse,"
                    + "membretel as Telephone,membreemail as Email "
                    + "from tb_membre where idmembre like ? or membrenom like ? or membreprenom like ?"; 
            //con=DriverManager.getConnection(chainConnection,user,password);
            pst=conn.prepareStatement(rek);
            pst.setString(1, txtrecherche.getText() + "%");
            pst.setString(2, txtrecherche.getText() + "%");
             pst.setString(3, txtrecherche.getText() + "%");
            rst = pst.executeQuery();
            tbmembre.setModel(DbUtils.resultSetToTableModel(rst));
             }
        
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null,"Erreur Requette"+ se.getMessage());
                
            }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajoutermembre;
    private javax.swing.JButton btnmodifiermembre;
    private javax.swing.JButton btnsup;
    private javax.swing.JButton btnvider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbmembre;
    private javax.swing.JTextField txtadressemembre;
    private javax.swing.JTextField txtemailmembre;
    private javax.swing.JTextField txtidmembre;
    private javax.swing.JTextField txtnommembre;
    private javax.swing.JTextField txtprenommembre;
    private javax.swing.JTextField txtrecherche;
    private javax.swing.JTextField txttelmembre;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
