/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestiontache.vue;

import com.gestiontache.controleur.ServiceIlocal;
import com.gestiontache.controleur.ServiceImpl;
import static com.gestiontache.controleur.ServiceImpl.conn;
import com.gestiontache.metier.Tache;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author samy
 */
public class AjoutertacheFr extends javax.swing.JInternalFrame {
ServiceIlocal se = new ServiceImpl();
	static List<Tache> listtach;
         public java.sql.Statement st;
	    public  ResultSet rst;
	    public static PreparedStatement pst;
            public Tache tache=new Tache();
    /**
     * Creates new form AjoutertacheFr
     */
    public AjoutertacheFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtidtache = new javax.swing.JTextField();
        txtnomtache = new javax.swing.JTextField();
        txtdatedebut = new javax.swing.JTextField();
        txtdatefin = new javax.swing.JTextField();
        txtetat = new javax.swing.JTextField();
        txtdesctache = new javax.swing.JTextField();
        btnajoutertache = new javax.swing.JButton();
        btnmodifiertache = new javax.swing.JButton();
        btnsuptache = new javax.swing.JButton();
        btnvider = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbtache = new javax.swing.JTable();
        txtrecherche = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Tache"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("ID tache");

        jLabel2.setText("Nom");

        jLabel3.setText("Description");

        jLabel4.setText("Date debut");

        jLabel5.setText("Date fin");

        jLabel6.setText("Etat");

        txtdatedebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatedebutActionPerformed(evt);
            }
        });

        btnajoutertache.setText("Ajouter");
        btnajoutertache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutertacheActionPerformed(evt);
            }
        });

        btnmodifiertache.setText("Modifier");
        btnmodifiertache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifiertacheActionPerformed(evt);
            }
        });

        btnsuptache.setText("Supprimer");
        btnsuptache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuptacheActionPerformed(evt);
            }
        });

        btnvider.setText("Vider");
        btnvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviderActionPerformed(evt);
            }
        });

        tbtache.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Tache", "Nom", "Description", "Date debut", "Date fin", "Etat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbtache.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbtacheMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbtache);
        if (tbtache.getColumnModel().getColumnCount() > 0) {
            tbtache.getColumnModel().getColumn(0).setResizable(false);
            tbtache.getColumnModel().getColumn(1).setResizable(false);
            tbtache.getColumnModel().getColumn(2).setResizable(false);
            tbtache.getColumnModel().getColumn(3).setResizable(false);
            tbtache.getColumnModel().getColumn(4).setResizable(false);
            tbtache.getColumnModel().getColumn(5).setResizable(false);
        }

        txtrecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrechercheKeyReleased(evt);
            }
        });

        jLabel8.setText("Rechercher");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnajoutertache)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnmodifiertache)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsuptache)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnvider))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtdesctache, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtnomtache, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtidtache, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtdatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdatefin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtetat, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidtache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnomtache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdesctache, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdatefin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtetat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajoutertache)
                    .addComponent(btnmodifiertache)
                    .addComponent(btnsuptache)
                    .addComponent(btnvider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrecherche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifiertacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifiertacheActionPerformed
        // TODO add your handling code here:
         tache.setTacheId(new Integer(txtidtache.getText()));
			tache.setTacheNom(txtnomtache.getText());
			tache.setTacheDescription(txtdesctache.getText());
			tache.setTacheDate_debut(txtdatedebut.getText());
			tache.setTacheDate_fin(txtdatefin.getText());
			tache.setTacheEtat(txtetat.getText());
		String rep=se.modifier_tache(tache);
		if(rep=="valider")
		{
			JOptionPane.showMessageDialog(AjoutertacheFr.this, "tache enregistre", "Information Message", 1);
			cleartextbox();
                        listetache();
                        Disablebutton();
		}
		else
		{
			JOptionPane.showMessageDialog(AjoutertacheFr.this, "Enregistrement echoue", "Information Message", 1);
			
		}
    }//GEN-LAST:event_btnmodifiertacheActionPerformed

    private void btnsuptacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuptacheActionPerformed
        // TODO add your handling code here:
         String rep=se.supprimer_tache(new Integer(txtidtache.getText()));
				if(rep=="valider")
				{
					JOptionPane.showMessageDialog(AjoutertacheFr.this, "tache supprime", "Information Message", 1);
					cleartextbox();
                                        listetache();
                                        Disablebutton();
				}
				else
				{
					JOptionPane.showMessageDialog(AjoutertacheFr.this, "Supression echoue", "Information Message", 1);
					
				}
    }//GEN-LAST:event_btnsuptacheActionPerformed

    private void btnviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviderActionPerformed
        // TODO add your handling code here:
        cleartextbox();
        Disablebutton();
    }//GEN-LAST:event_btnviderActionPerformed

    private void txtdatedebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatedebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatedebutActionPerformed
  
    private void btnajoutertacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutertacheActionPerformed
        // TODO add your handling code here:
                         tache.setTacheId(new Integer(txtidtache.getText()));
			tache.setTacheNom(txtnomtache.getText());
			tache.setTacheDescription(txtdesctache.getText());
			tache.setTacheDate_debut(txtdatedebut.getText());
			tache.setTacheDate_fin(txtdatefin.getText());
			tache.setTacheEtat(txtetat.getText());
		String rep=	se.ajouter_tache(tache);	
		if(rep=="valider")
		{
			JOptionPane.showMessageDialog(AjoutertacheFr.this, "tache enregistre", "Information Message", 1);
			cleartextbox();
                        listetache();
                        Disablebutton();
		}
		else
		{
			JOptionPane.showMessageDialog(AjoutertacheFr.this, "Enregistrement echoue", "Information Message", 1);
			
		}
    }//GEN-LAST:event_btnajoutertacheActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        listetache();
      Disablebutton();
     
    }//GEN-LAST:event_formInternalFrameOpened

    private void tbtacheMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtacheMousePressed
        // TODO add your handling code here:
         int index = tbtache.getSelectedRow();
        TableModel mod = tbtache.getModel();
        Enablebutton();
        txtidtache.setText(mod.getValueAt(index, 0).toString());
        txtnomtache.setText(mod.getValueAt(index, 1).toString());
        txtdesctache.setText(mod.getValueAt(index, 2).toString());
        txtdatedebut.setText(mod.getValueAt(index, 3).toString());
        txtdatefin.setText(mod.getValueAt(index, 4).toString());
       txtetat.setText(mod.getValueAt(index, 5).toString());
  
                                         
    }//GEN-LAST:event_tbtacheMousePressed

    private void txtrechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrechercheKeyReleased
        // TODO add your handling code here:
        rechercherpar();
    }//GEN-LAST:event_txtrechercheKeyReleased
/*Clear textbox */
	private void cleartextbox() {
		// TODO Auto-generated method stub
		txtidtache.setText(null);
		txtnomtache.setText(null);
		txtdesctache.setText(null);
		txtdatedebut.setText(null);
		txtdatefin.setText(null);
		txtetat.setText(null);
	
	}
        private void Disablebutton() {
		// TODO Auto-generated method stub
                btnajoutertache.setEnabled(true);
		btnmodifiertache.setEnabled(false);
                btnvider.setEnabled(false);
                btnsuptache.setEnabled(false);	
	}
         private void Enablebutton() {
		// TODO Auto-generated method stub
                 btnajoutertache.setEnabled(false);
		btnmodifiertache.setEnabled(true);
                btnvider.setEnabled(true);
                btnsuptache.setEnabled(true);	
	}
        public  void listetache() {
	try 
        {
            String rek="Select idtache as ID,tachenom as Nom,tachedescription as Description,tachedate_debut as Date_debut,"
                    + "tachedate_fin as Date_fin,tacheetat as Etat "
                    + "from tb_tache "; 
            //con=DriverManager.getConnection(chainConnection,user,password);
            pst=conn.prepareStatement(rek);
            rst = pst.executeQuery();
            tbtache.setModel(DbUtils.resultSetToTableModel(rst));
             }
        
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null,"Erreur Requette"+ se.getMessage());
                
            }
	
}
        public  void rechercherpar() {
         try 
        {
            String rek="Select idtache as ID ,tachenom as Nom,tachedescription as Description,tachedate_debut as Date_debut,"
                    + "tachedate_fin as Date_fin,tacheetat as Etat "
                    + "from tb_tache where idtache like ? or tachenom like ? or tachedescription like ?"; 
            //con=DriverManager.getConnection(chainConnection,user,password);
            pst=conn.prepareStatement(rek);
            pst.setString(1, txtrecherche.getText() + "%");
            pst.setString(2, txtrecherche.getText() + "%");
             pst.setString(3, txtrecherche.getText() + "%");
            rst = pst.executeQuery();
            tbtache.setModel(DbUtils.resultSetToTableModel(rst));
             }
        
            catch(SQLException se)
            {
                JOptionPane.showMessageDialog(null,"Erreur Requette"+ se.getMessage());
                
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajoutertache;
    private javax.swing.JButton btnmodifiertache;
    private javax.swing.JButton btnsuptache;
    private javax.swing.JButton btnvider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbtache;
    private javax.swing.JTextField txtdatedebut;
    private javax.swing.JTextField txtdatefin;
    private javax.swing.JTextField txtdesctache;
    private javax.swing.JTextField txtetat;
    private javax.swing.JTextField txtidtache;
    private javax.swing.JTextField txtnomtache;
    private javax.swing.JTextField txtrecherche;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
