/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestiontache.vue;

import java.awt.Desktop;

/**
 *
 * @author samy
 */
public class MenuFr extends javax.swing.JFrame {

    /**
     * Creates new form MenuFr
     */
    public MenuFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        smnajouterm = new javax.swing.JMenuItem();
        smnrechercherm = new javax.swing.JMenuItem();
        smnlisterm = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        smnajoutert = new javax.swing.JMenuItem();
        smnrecherchet = new javax.swing.JMenuItem();
        smnlistert = new javax.swing.JMenuItem();
        smnassignert = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktop.setName("desktop2"); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(232, 232, 232));
        jMenuBar1.setForeground(new java.awt.Color(126, 126, 126));

        jMenu1.setBackground(new java.awt.Color(177, 177, 177));
        jMenu1.setForeground(new java.awt.Color(106, 104, 99));
        jMenu1.setText("Membre");
        jMenu1.setName(""); // NOI18N

        smnajouterm.setText("Ajouter");
        smnajouterm.setName("mnAjoutmembre"); // NOI18N
        smnajouterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnajoutermActionPerformed(evt);
            }
        });
        jMenu1.add(smnajouterm);

        smnrechercherm.setLabel("Rechercher");
        smnrechercherm.setName("mnrecherchememb"); // NOI18N
        smnrechercherm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnrecherchermActionPerformed(evt);
            }
        });
        jMenu1.add(smnrechercherm);

        smnlisterm.setText("Lister tache");
        smnlisterm.setName("mnlistermemb"); // NOI18N
        smnlisterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnlistermActionPerformed(evt);
            }
        });
        jMenu1.add(smnlisterm);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(95, 95, 93));
        jMenu2.setText("Tache");
        jMenu2.setName("mnajouttache"); // NOI18N

        smnajoutert.setText("Ajouter");
        smnajoutert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnajoutertActionPerformed(evt);
            }
        });
        jMenu2.add(smnajoutert);

        smnrecherchet.setText("Rechercher");
        smnrecherchet.setName("mnrecherchertach"); // NOI18N
        jMenu2.add(smnrecherchet);

        smnlistert.setText("Lister");
        smnlistert.setName("mnlistertach"); // NOI18N
        jMenu2.add(smnlistert);

        smnassignert.setText("Assigner tache");
        smnassignert.setName("mnassignertach"); // NOI18N
        smnassignert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnassignertActionPerformed(evt);
            }
        });
        jMenu2.add(smnassignert);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnrecherchermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnrecherchermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smnrecherchermActionPerformed

    private void smnajoutermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnajoutermActionPerformed
        // TODO add your handling code here:
        AjoutermembreFr amf= new AjoutermembreFr();
	desktop.add(amf);
        amf.show();
    }//GEN-LAST:event_smnajoutermActionPerformed

    private void smnlistermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnlistermActionPerformed
        // TODO add your handling code here:
        ListertachemembreFr lmf= new ListertachemembreFr();
	desktop.add(lmf);
        lmf.show();
    }//GEN-LAST:event_smnlistermActionPerformed

    private void smnajoutertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnajoutertActionPerformed
        // TODO add your handling code here:
        AjoutertacheFr atf= new AjoutertacheFr();
	desktop.add(atf);
        atf.show();
    }//GEN-LAST:event_smnajoutertActionPerformed

    private void smnassignertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnassignertActionPerformed
        // TODO add your handling code here:
        AssigneTacheFr ast= new AssigneTacheFr();
	desktop.add(ast);
        ast.show();
    }//GEN-LAST:event_smnassignertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem smnajouterm;
    private javax.swing.JMenuItem smnajoutert;
    private javax.swing.JMenuItem smnassignert;
    private javax.swing.JMenuItem smnlisterm;
    private javax.swing.JMenuItem smnlistert;
    private javax.swing.JMenuItem smnrechercherm;
    private javax.swing.JMenuItem smnrecherchet;
    // End of variables declaration//GEN-END:variables
}
